USE AWSInvest;
GO

IF OBJECT_ID('BSEG') IS NOT NULL
  DELETE FROM BSEG WHERE GJAHR = 2023;
ELSE
  CREATE TABLE BSEG (
    ID int IDENTITY(1, 1) PRIMARY KEY CLUSTERED,
    BUKRS smallint,
    BELNR bigint,
    GJAHR smallint,
    BUZEI tinyint,
    AUGDT date,
    AUGCP date,
    AUGBL int,
    BSCHL tinyint,
    KOART nchar(1),
    UMSKZ nchar(1),
    SHKZG nchar(1),
    GSBER nchar(4),
    MWSKZ nchar(2),
    DMBTR money,
    WRBTR money,
    KZBTR money,
    PSWBT money,
    PSWSL nchar(3),
    MWSTS money,
    WMWST money,
    HWBAS money,
    FWBAS money,
    SHZUZ nchar(1),
    TXGRP tinyint,
    KTOSL nchar(3),
    VALUT date,
    ZUONR nvarchar(20),
    SGTXT nvarchar(100),
    VBUND smallint,
    BEWAR tinyint,
    VORGN nchar(4),
    KOKRS smallint,
    KOSTL int,
    AUFNR nchar(8),
    ANBWA tinyint,
    XUMSW nchar(1),
    XAUTO nchar(1),
    XZAHL nchar(1),
    SAKNR int,
    HKONT int,
    LIFNR int,
    HZUON int,
    ZFBDT date,
    ZTERM nchar(4),
    ZBD1T smallint,
    ZBD2T smallint,
    ZBD3T smallint,
    ZBD1P numeric(6, 3),
    ZBD2P numeric(6, 3),
    SKFBT numeric(12, 2),
    SKNTO numeric(10, 2),
    WSKTO numeric(10, 2),
    ZLSCH nchar(1),
    ZLSPR nchar(1),
    HBKID nchar(5),
    NEBTR numeric(12, 2),
    MWSK1 nchar(2),
    DMBT1 numeric(10, 2),
    WRBT1 numeric(10, 2),
    MWSK2 nchar(2),
    DMBT2 numeric(10, 2),
    WRBT2 numeric(10, 2),
    MWSK3 nchar(2),
    DMBT3 numeric(10, 2),
    WRBT3 numeric(10, 2),
    REBZG bigint,
    REBZJ smallint,
    REBZZ tinyint,
    REBZT nchar(1),
    TBTKZ nchar(1),
    STCEG nchar(11),
    EGBLD nchar(2),
    EGLLD nchar(2),
    RDIFF money,
    XHKOM nchar(1),
    HWMET nchar(1),
    XRAGL nchar(1),
    XNEGP nchar(1),
    XREF3 nvarchar(30),
    KIDNO nchar(1),
    AGZEI tinyint,
    AUGGJ smallint,
    HKTID nchar(5)
  )

INSERT INTO BSEG (BUKRS, BELNR, GJAHR, BUZEI, AUGDT, AUGCP, AUGBL, BSCHL, KOART, UMSKZ, SHKZG, GSBER, MWSKZ, DMBTR, WRBTR, KZBTR, PSWBT, PSWSL, MWSTS, WMWST, HWBAS, FWBAS, SHZUZ, TXGRP, KTOSL, VALUT, ZUONR, SGTXT, VBUND, BEWAR, VORGN, KOKRS, KOSTL, AUFNR, ANBWA, XUMSW, XAUTO, XZAHL, SAKNR, HKONT, LIFNR, HZUON, ZFBDT, ZTERM, ZBD1T, ZBD2T, ZBD3T, ZBD1P, ZBD2P, SKFBT, SKNTO, WSKTO, ZLSCH, ZLSPR, HBKID, NEBTR, MWSK1, DMBT1, WRBT1, MWSK2, DMBT2, WRBT2, MWSK3, DMBT3, WRBT3, REBZG, REBZJ, REBZZ, REBZT, TBTKZ, STCEG, EGBLD, EGLLD, RDIFF, XHKOM, HWMET, XRAGL, XNEGP, XREF3, KIDNO, AGZEI, AUGGJ, HKTID)
SELECT CAST(BUKRS AS smallint),
  CAST(BELNR AS bigint),
  CAST(GJAHR AS smallint),
  CAST(BUZEI AS tinyint),
  CONVERT(date, AUGDT, 104),
  CONVERT(date, AUGCP, 104),
  CAST(AUGBL AS int),
  CAST(BSCHL AS tinyint),
  CAST(KOART AS nchar(1)),
  CAST(UMSKZ AS nchar(1)),
  CAST(SHKZG AS nchar(1)),
  CAST(GSBER AS nchar(4)),
  CAST(MWSKZ AS nchar(2)),
  CAST(REPLACE(REPLACE(DMBTR, N',', N'.'), N' ', N'') AS money),
  CAST(REPLACE(REPLACE(WRBTR, N',', N'.'), N' ', N'') AS money),
  CAST(REPLACE(REPLACE(KZBTR, N',', N'.'), N' ', N'') AS money),
  CAST(REPLACE(REPLACE(PSWBT, N',', N'.'), N' ', N'') AS money),
  CAST(PSWSL AS nchar(3)),
  CAST(REPLACE(REPLACE(MWSTS, N',', N'.'), N' ', N'') AS money),
  CAST(REPLACE(REPLACE(WMWST, N',', N'.'), N' ', N'') AS money),
  CAST(REPLACE(REPLACE(HWBAS, N',', N'.'), N' ', N'') AS money),
  CAST(REPLACE(REPLACE(FWBAS, N',', N'.'), N' ', N'') AS money),
  CAST(SHZUZ AS nchar(1)),
  CAST(TXGRP AS tinyint),
  CAST(KTOSL AS nchar(3)),
  CONVERT(date, VALUT, 104),
  CAST(ZUONR AS nvarchar(20)),
  CAST(SGTXT AS nvarchar(100)),
  CAST(VBUND AS smallint),
  CAST(BEWAR AS tinyint),
  CAST(VORGN AS nchar(4)),
  CAST(KOKRS AS smallint),
  CAST(KOSTL AS int),
  CAST(AUFNR AS nchar(8)),
  CAST(ANBWA AS tinyint),
  CAST(XUMSW AS nchar(1)),
  CAST(XAUTO AS nchar(1)),
  CAST(XZAHL AS nchar(1)),
  CAST(SAKNR AS int),
  CAST(HKONT AS int),
  CAST(LIFNR AS int),
  CAST(HZUON AS int),
  CONVERT(date, ZFBDT, 104),
  CAST(ZTERM AS nchar(4)),
  CAST(ZBD1T AS smallint),
  CAST(ZBD2T AS smallint),
  CAST(ZBD3T AS smallint),
  CAST(REPLACE(REPLACE(ZBD1P, N',', N'.'), N' ', N'') AS numeric(4, 1)),
  CAST(REPLACE(REPLACE(ZBD2P, N',', N'.'), N' ', N'') AS numeric(4, 1)),
  CAST(REPLACE(REPLACE(SKFBT, N',', N'.'), N' ', N'') AS numeric(12, 2)),
  CAST(REPLACE(REPLACE(SKNTO, N',', N'.'), N' ', N'') AS numeric(10, 2)),
  CAST(REPLACE(REPLACE(WSKTO, N',', N'.'), N' ', N'') AS numeric(10, 2)),
  CAST(ZLSCH AS nchar(1)),
  CAST(ZLSPR AS nchar(1)),
  CAST(HBKID AS nchar(5)),
  CAST(REPLACE(REPLACE(NEBTR, N',', N'.'), N' ', N'') AS numeric(12, 2)),
  CAST(MWSK1 AS nchar(2)),
  CAST(REPLACE(REPLACE(DMBT1, N',', N'.'), N' ', N'') AS numeric(10, 2)),
  CAST(REPLACE(REPLACE(WRBT1, N',', N'.'), N' ', N'') AS numeric(10, 2)),
  CAST(MWSK2 AS nchar(2)),
  CAST(REPLACE(REPLACE(DMBT2, N',', N'.'), N' ', N'') AS numeric(10, 2)),
  CAST(REPLACE(REPLACE(WRBT2, N',', N'.'), N' ', N'') AS numeric(10, 2)),
  CAST(MWSK3 AS nchar(2)),
  CAST(REPLACE(REPLACE(DMBT3, N',', N'.'), N' ', N'') AS numeric(10, 2)),
  CAST(REPLACE(REPLACE(WRBT3, N',', N'.'), N' ', N'') AS numeric(10, 2)),
  CAST(REBZG AS bigint),
  CAST(REBZJ AS smallint),
  CAST(REBZZ AS tinyint),
  CAST(REBZT AS nchar(1)),
  CAST(TBTKZ AS nchar(1)),
  CAST(STCEG AS nchar(11)),
  CAST(EGBLD AS nchar(2)),
  CAST(EGLLD AS nchar(2)),
  CAST(REPLACE(REPLACE(RDIFF, N',', N'.'), N' ', N'') AS money),
  CAST(XHKOM AS nchar(1)),
  CAST(HWMET AS nchar(1)),
  CAST(XRAGL AS nchar(1)),
  CAST(XNEGP AS nchar(1)),
  CAST(XREF3 AS nvarchar(30)),
  CAST(KIDNO AS nchar(1)),
  CAST(AGZEI AS tinyint),
  CAST(AUGGJ AS smallint),
  CAST(HKTID AS nchar(5))
FROM BSEG_Import;

GO

DROP TABLE BSEG_Import;
GO