SELECT KdNr,
  VsaNr,
  DENSE_RANK() OVER (ORDER BY Nachname, Vorname) Traeger,
  Vorname,
  Nachname,
  [Personalnummer ] AS PersNr,
  KSt AS Kostenstelle,
  NULL AS Sortierschluessel,
  NULL AS Schrank,
  NULL AS Fach,
  0 AS Menge,
  ArtikelNr,
  NULL AS ArtikelBez,
  Variante,
  Groesse,
  0 AS Aufkauf,
  N'J' AS mitNS,
  N'J' AS mitEm,
  NULL AS Titel,
  NULL AS Änderungsart1,
  NULL AS Änderungsmass1,
  NULL AS ÄnderungsPlatzierung1,
  NULL AS Änderungsart2,
  NULL AS Änderungsmass2,
  NULL AS ÄnderungsPlatzierung2,
  NULL AS Änderungsart3,
  NULL AS Änderungsmass3,
  NULL AS ÄnderungsPlatzierung3,
  NULL AS Namensschild_Zeile_2,
  NULL AS Folge_ArtikelNr,
  NULL AS Folge_ArtikelBez,
  NULL AS Folge_Groesse,
  NULL AS Folge_Variante,
  NULL AS Folge_Änderungsart1,
  NULL AS Folge_Änderungsmass1,
  NULL AS Folge_ÄnderungsPlatzierung1,
  NULL AS Folge_Änderungsart2,
  NULL AS Folge_Änderungsmass2,
  NULL AS Folge_ÄnderungsPlatzierung2,
  NULL AS Folge_Änderungsart3,
  NULL AS Folge_Änderungsmass3,
  NULL AS Folge_ÄnderungsPlatzierung3,
  NULL AS Sonstiges,
  NULL AS Kommentare,
  NULL AS Abschluss
FROM _IT78713
GROUP BY KdNr, VsaNr, Kst, Vorname, Nachname, [Personalnummer ], ArtikelNr, Groesse, Variante

GO