USE [master]
GO
ALTER DATABASE [Salesianer] SET QUERY_STORE = ON
GO
ALTER DATABASE [Salesianer] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, INTERVAL_LENGTH_MINUTES = 30, MAX_STORAGE_SIZE_MB = 2000)
GO
