USE [master]
GO
ALTER DATABASE [Salesianer] SET QUERY_STORE = ON
GO
ALTER DATABASE [Salesianer] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, INTERVAL_LENGTH_MINUTES = 30, MAX_STORAGE_SIZE_MB = 2000)
GO

ALTER DATABASE [Salesianer] SET QUERY_STORE = ON
GO
ALTER DATABASE [Salesianer] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, INTERVAL_LENGTH_MINUTES = 30, MAX_STORAGE_SIZE_MB = 5000, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 14), QUERY_CAPTURE_MODE = CUSTOM, QUERY_CAPTURE_POLICY = (EXECUTION_COUNT = 100, TOTAL_EXECUTION_CPU_TIME_MS = 10000))
GO