USE [master]
GO
ALTER DATABASE [SalesianerSA22] SET QUERY_STORE CLEAR;
GO
ALTER DATABASE [SalesianerSA22] SET QUERY_STORE = ON
GO
ALTER DATABASE [SalesianerSA22] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, INTERVAL_LENGTH_MINUTES = 30, MAX_STORAGE_SIZE_MB = 2048, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 14), QUERY_CAPTURE_MODE = CUSTOM, QUERY_CAPTURE_POLICY = (EXECUTION_COUNT = 100, TOTAL_EXECUTION_CPU_TIME_MS = 10000))
GO

/* SQL 2017: */
/*
USE [master]
GO
ALTER DATABASE [Salesianer_SA22] SET QUERY_STORE CLEAR;
GO
ALTER DATABASE [Salesianer_SA22] SET QUERY_STORE = ON
GO
ALTER DATABASE [Salesianer_SA22] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, INTERVAL_LENGTH_MINUTES = 30, MAX_STORAGE_SIZE_MB = 2048, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 14), QUERY_CAPTURE_MODE = AUTO)
GO
*/

/* SAWR */
USE [master]
GO
ALTER DATABASE [Salesianer_SAWR] SET QUERY_STORE CLEAR;
GO
ALTER DATABASE [Salesianer_SAWR] SET QUERY_STORE = ON
GO
ALTER DATABASE [Salesianer_SAWR] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), INTERVAL_LENGTH_MINUTES = 30, MAX_STORAGE_SIZE_MB = 2048);
GO