CREATE TABLE #TmpStellplatz (Tour char(10), Stellplatz char(50));
INSERT INTO #TmpStellplatz VALUES ('1-101', 'Enns 3/B');
INSERT INTO #TmpStellplatz VALUES ('1-201', 'Enns 3/B');
INSERT INTO #TmpStellplatz VALUES ('1-301', 'Enns 3/B');
INSERT INTO #TmpStellplatz VALUES ('1-401', 'Enns 3/B');
INSERT INTO #TmpStellplatz VALUES ('1-501', 'Enns 3/B');
INSERT INTO #TmpStellplatz VALUES ('1-102', 'Linz');
INSERT INTO #TmpStellplatz VALUES ('1-202', 'Linz');
INSERT INTO #TmpStellplatz VALUES ('1-302', 'Linz');
INSERT INTO #TmpStellplatz VALUES ('1-402', 'Linz');
INSERT INTO #TmpStellplatz VALUES ('1-502', 'Linz');
INSERT INTO #TmpStellplatz VALUES ('1-103', 'Enns 4/A');
INSERT INTO #TmpStellplatz VALUES ('1-203', 'Enns 4/A');
INSERT INTO #TmpStellplatz VALUES ('1-303', 'Enns 4/A');
INSERT INTO #TmpStellplatz VALUES ('1-403', 'Enns 4/A');
INSERT INTO #TmpStellplatz VALUES ('1-503', 'Enns 4/A');
INSERT INTO #TmpStellplatz VALUES ('1-104', 'Enns 5/A');
INSERT INTO #TmpStellplatz VALUES ('1-204', 'Enns 5/A');
INSERT INTO #TmpStellplatz VALUES ('1-404', 'Enns 5/A');
INSERT INTO #TmpStellplatz VALUES ('1-504', 'Enns 5/A');
INSERT INTO #TmpStellplatz VALUES ('1-105', 'Enns 5/B');
INSERT INTO #TmpStellplatz VALUES ('1-205', 'Enns 2/A');
INSERT INTO #TmpStellplatz VALUES ('1-305', 'Enns 5/A');
INSERT INTO #TmpStellplatz VALUES ('1-405', 'Enns 2/A');
INSERT INTO #TmpStellplatz VALUES ('1-505', 'Enns 5/B');
INSERT INTO #TmpStellplatz VALUES ('1-106', 'Enns 2/B');
INSERT INTO #TmpStellplatz VALUES ('1-206', 'Enns 2/B');
INSERT INTO #TmpStellplatz VALUES ('1-306', 'Enns 2/B');
INSERT INTO #TmpStellplatz VALUES ('1-406', 'Enns 2/B');
INSERT INTO #TmpStellplatz VALUES ('1-506', 'Enns 2/B');
INSERT INTO #TmpStellplatz VALUES ('1-110', 'Enns MPZ');
INSERT INTO #TmpStellplatz VALUES ('1-210', 'Enns MPZ');
INSERT INTO #TmpStellplatz VALUES ('1-310', 'Enns MPZ');
INSERT INTO #TmpStellplatz VALUES ('1-410', 'Enns MPZ');
INSERT INTO #TmpStellplatz VALUES ('1-510', 'Enns MPZ');
INSERT INTO #TmpStellplatz VALUES ('1-108', 'Enns 1/B');
INSERT INTO #TmpStellplatz VALUES ('1-208', 'Enns 1/B');
INSERT INTO #TmpStellplatz VALUES ('1-408', 'Enns 1/B');
INSERT INTO #TmpStellplatz VALUES ('1-508', 'Enns 1/B');
INSERT INTO #TmpStellplatz VALUES ('1-109', 'Enns 3/A');
INSERT INTO #TmpStellplatz VALUES ('1-209', 'Enns 3/A');
INSERT INTO #TmpStellplatz VALUES ('1-409', 'Enns 3/A');
INSERT INTO #TmpStellplatz VALUES ('1-509', 'Enns 3/A');
INSERT INTO #TmpStellplatz VALUES ('1-609', 'Enns 3/A');
INSERT INTO #TmpStellplatz VALUES ('1-107', 'Enns 4/B');
INSERT INTO #TmpStellplatz VALUES ('1-207', 'Enns 4/B');
INSERT INTO #TmpStellplatz VALUES ('1-307', 'Enns 4/B');
INSERT INTO #TmpStellplatz VALUES ('1-407', 'Enns 4/B');
INSERT INTO #TmpStellplatz VALUES ('1-507', 'Enns 4/B');
INSERT INTO #TmpStellplatz VALUES ('1-607', 'Enns 3/C');
INSERT INTO #TmpStellplatz VALUES ('1-111', 'Enns, MPZ');
INSERT INTO #TmpStellplatz VALUES ('1-211', 'Enns, MPZ');
INSERT INTO #TmpStellplatz VALUES ('1-311', 'Enns, MPZ');
INSERT INTO #TmpStellplatz VALUES ('1-411', 'Enns, MPZ');
INSERT INTO #TmpStellplatz VALUES ('1-511', 'Enns, MPZ');
INSERT INTO #TmpStellplatz VALUES ('1-112', 'Enns, MPZ');
INSERT INTO #TmpStellplatz VALUES ('1-212', 'Enns, MPZ');
INSERT INTO #TmpStellplatz VALUES ('1-312', 'Enns, MPZ');
INSERT INTO #TmpStellplatz VALUES ('1-412', 'Enns, MPZ');
INSERT INTO #TmpStellplatz VALUES ('1-512', 'Enns, MPZ');
INSERT INTO #TmpStellplatz VALUES ('1-114', 'Enns 3/C + Linz');
INSERT INTO #TmpStellplatz VALUES ('1-214', 'Enns 3/C');
INSERT INTO #TmpStellplatz VALUES ('1-314', 'Enns 3/C + Linz');
INSERT INTO #TmpStellplatz VALUES ('1-414', 'Enns 3/C');
INSERT INTO #TmpStellplatz VALUES ('1-514', 'Enns 3/C + Linz');
INSERT INTO #TmpStellplatz VALUES ('1-614', 'Enns 2/C');
INSERT INTO #TmpStellplatz VALUES ('1-115', 'Enns 2/A');
INSERT INTO #TmpStellplatz VALUES ('1-215', 'Enns 2/C');
INSERT INTO #TmpStellplatz VALUES ('1-415', 'Enns 2/C');
INSERT INTO #TmpStellplatz VALUES ('1-515', 'Enns, 2/A ');
INSERT INTO #TmpStellplatz VALUES ('1-615', 'Linz');
INSERT INTO #TmpStellplatz VALUES ('1-116', 'Enns, 5/B und Linz');
INSERT INTO #TmpStellplatz VALUES ('1-216', 'Enns, 5/B  ');
INSERT INTO #TmpStellplatz VALUES ('1-316', 'Enns, 5/B und Linz');
INSERT INTO #TmpStellplatz VALUES ('1-416', 'Enns, 5/B und Linz');
INSERT INTO #TmpStellplatz VALUES ('1-516', 'Enns, 5/B und Linz');
INSERT INTO #TmpStellplatz VALUES ('1-117', 'Enns, 4/C und Linz');
INSERT INTO #TmpStellplatz VALUES ('1-317', 'Enns, 4/C und Linz');
INSERT INTO #TmpStellplatz VALUES ('1-417', 'Enns, 4/C und Linz');
INSERT INTO #TmpStellplatz VALUES ('1-517', 'Enns, 4/C und Linz');
INSERT INTO #TmpStellplatz VALUES ('2-201', 'Lenzing, Q ');
INSERT INTO #TmpStellplatz VALUES ('2-301', 'Lenzing, O');
INSERT INTO #TmpStellplatz VALUES ('2-401', 'Lenzing, O');
INSERT INTO #TmpStellplatz VALUES ('2-501', 'Lenzing, Q ');
INSERT INTO #TmpStellplatz VALUES ('2-103', 'Lenzing A + B');
INSERT INTO #TmpStellplatz VALUES ('2-203', 'Lenzing A + B');
INSERT INTO #TmpStellplatz VALUES ('2-303', 'Lenzing A + B');
INSERT INTO #TmpStellplatz VALUES ('2-403', 'Lenzing A + B');
INSERT INTO #TmpStellplatz VALUES ('2-503', 'Lenzing A + B');
INSERT INTO #TmpStellplatz VALUES ('2-104', 'Lenzing C + D ');
INSERT INTO #TmpStellplatz VALUES ('2-204', 'Lenzing C + D ');
INSERT INTO #TmpStellplatz VALUES ('2-304', 'Lenzing C + D ');
INSERT INTO #TmpStellplatz VALUES ('2-404', 'Lenzing T');
INSERT INTO #TmpStellplatz VALUES ('2-504', 'Lenzing C + D ');
INSERT INTO #TmpStellplatz VALUES ('2-105', 'Lenzing U + V ');
INSERT INTO #TmpStellplatz VALUES ('2-205', 'Lenzing U + V ');
INSERT INTO #TmpStellplatz VALUES ('2-305', 'Lenzing U + V ');
INSERT INTO #TmpStellplatz VALUES ('2-505', 'Lenzing U + V ');
INSERT INTO #TmpStellplatz VALUES ('2-106', 'Lenzing F +  L');
INSERT INTO #TmpStellplatz VALUES ('2-206', 'Lenzing F +  L');
INSERT INTO #TmpStellplatz VALUES ('2-306', 'Lenzing F +  L');
INSERT INTO #TmpStellplatz VALUES ('2-406', 'Lenzing F +  L');
INSERT INTO #TmpStellplatz VALUES ('2-506', 'Lenzing F +  L');
INSERT INTO #TmpStellplatz VALUES ('2-107', 'Lenzing  R');
INSERT INTO #TmpStellplatz VALUES ('2-307', 'Lenzing  R');
INSERT INTO #TmpStellplatz VALUES ('2-407', 'Lenzing  R');
INSERT INTO #TmpStellplatz VALUES ('2-507', 'Lenzing  R');
INSERT INTO #TmpStellplatz VALUES ('2-607', 'Lenzing  N');
INSERT INTO #TmpStellplatz VALUES ('2-109', 'Lenzing  Q');
INSERT INTO #TmpStellplatz VALUES ('2-209', 'Lenzing  R');
INSERT INTO #TmpStellplatz VALUES ('2-409', 'Lenzing  Q');
INSERT INTO #TmpStellplatz VALUES ('2-509', 'Lenzing  P');
INSERT INTO #TmpStellplatz VALUES ('2-210', 'Lenzing  O');
INSERT INTO #TmpStellplatz VALUES ('2-310', 'Lenzing  Q');
INSERT INTO #TmpStellplatz VALUES ('2-410', 'Lenzing  N');
INSERT INTO #TmpStellplatz VALUES ('2-510', 'Lenzing  MBK');
INSERT INTO #TmpStellplatz VALUES ('2-610', 'Lenzing  B');
INSERT INTO #TmpStellplatz VALUES ('2-112', 'Lenzing  M');
INSERT INTO #TmpStellplatz VALUES ('2-212', 'Lenzing  N');
INSERT INTO #TmpStellplatz VALUES ('2-412', 'Lenzing  M');
INSERT INTO #TmpStellplatz VALUES ('2-512', 'Lenzing  N');
INSERT INTO #TmpStellplatz VALUES ('2-113', 'Lenzing  O + P');
INSERT INTO #TmpStellplatz VALUES ('2-213', 'Lenzing  M + L ');
INSERT INTO #TmpStellplatz VALUES ('2-413', 'Lenzing  C + D ');
INSERT INTO #TmpStellplatz VALUES ('2-513', 'Lenzing  M + L ');
INSERT INTO #TmpStellplatz VALUES ('2-114', 'Lenzing  S');
INSERT INTO #TmpStellplatz VALUES ('2-214', 'Lenzing  B');
INSERT INTO #TmpStellplatz VALUES ('2-314', 'Lenzing  P');
INSERT INTO #TmpStellplatz VALUES ('2-514', 'Lenzing  O');
INSERT INTO #TmpStellplatz VALUES ('2-116', 'Lenzing  F +  L ');
INSERT INTO #TmpStellplatz VALUES ('2-216', 'Lenzing  F +  L ');
INSERT INTO #TmpStellplatz VALUES ('2-316', 'Lenzing  F +  L ');
INSERT INTO #TmpStellplatz VALUES ('2-416', 'Lenzing  F +  L ');
INSERT INTO #TmpStellplatz VALUES ('2-516', 'Lenzing  F +  L ');
INSERT INTO #TmpStellplatz VALUES ('2-119', 'Lenzing  C + H');
INSERT INTO #TmpStellplatz VALUES ('2-219', 'Lenzing  C + H');
INSERT INTO #TmpStellplatz VALUES ('2-319', 'Lenzing  C + H');
INSERT INTO #TmpStellplatz VALUES ('2-419', 'Lenzing  C + H');
INSERT INTO #TmpStellplatz VALUES ('2-519', 'Lenzing  C + H');
INSERT INTO #TmpStellplatz VALUES ('2-120', 'Lenzing  C + D ');
INSERT INTO #TmpStellplatz VALUES ('2-220', 'Lenzing  C + D ');
INSERT INTO #TmpStellplatz VALUES ('2-320', 'Lenzing  C + D ');
INSERT INTO #TmpStellplatz VALUES ('2-420', 'Lenzing  T');
INSERT INTO #TmpStellplatz VALUES ('2-520', 'Lenzing  C + D ');
INSERT INTO #TmpStellplatz VALUES ('2-121', 'Lenzing U + V ');
INSERT INTO #TmpStellplatz VALUES ('2-221', 'Lenzing U + V ');
INSERT INTO #TmpStellplatz VALUES ('2-321', 'Lenzing U + V ');
INSERT INTO #TmpStellplatz VALUES ('2-421', 'Lenzing U + V ');
INSERT INTO #TmpStellplatz VALUES ('2-521', 'Lenzing U + V ');
INSERT INTO #TmpStellplatz VALUES ('2-123', 'Lenzing MBK');
INSERT INTO #TmpStellplatz VALUES ('2-323', 'Lenzing MBK');
INSERT INTO #TmpStellplatz VALUES ('2-423', 'Lenzing MBK');
INSERT INTO #TmpStellplatz VALUES ('2-124', 'Lenzing N');
INSERT INTO #TmpStellplatz VALUES ('2-224', 'Lenzing B');
INSERT INTO #TmpStellplatz VALUES ('2-324', 'Lenzing N');
INSERT INTO #TmpStellplatz VALUES ('2-424', 'Lenzing P');

UPDATE Touren SET StellplatzExpedi = x.Stellplatz
FROM Touren, #TmpStellplatz x
WHERE LEFT(Touren.Tour, 5) = TRIM(x.Tour);

DROP TABLE #TmpStellplatz;