DECLARE @sourceid int = 25209;
DECLARE @userid int = (SELECT ID FROM Mitarbei WHERE UserName = UPPER(REPLACE(ORIGINAL_LOGIN(), N'SAL\', N'')));

DECLARE @NewZahlZiel TABLE (
  TermNumber nchar(4) COLLATE Latin1_General_CS_AS,
  DaysToPay int,
  Discount numeric(18,4)
);

INSERT INTO @NewZahlZiel (TermNumber, DaysToPay, Discount)
VALUES (N'HR12', 15, 2.00),
       (N'HR13', 15, 4.50),
       (N'HR14', 15, 3.00),
       (N'HR15', 60, 6.75);

INSERT INTO ZahlZiel (ZahlZiel, ZahlZielBez, ZahlZielBez1, ZahlZielBez2, ZahlZielBez3, ZahlZielBez4, ZahlZielBez5, ZahlZielBez6, ZahlZielBez7, ZahlZielBez8, ZahlZielBez9, ZahlZielBezA, BezDruckMemo, BezDruckMemo1, BezDruckMemo2, BezDruckMemo3, BezDruckMemo4, BezDruckMemo5, BezDruckMemo6, BezDruckMemo7, BezDruckMemo8, BezDruckMemo9, BezDruckMemoA, BezDruckGMemo, BezDruckGMemo1, BezDruckGMemo2, BezDruckGMemo3, BezDruckGMemo4, BezDruckGMemo5, BezDruckGMemo6, BezDruckGMemo7, BezDruckGMemo8, BezDruckGMemo9, BezDruckGMemoA, BezDruckGLSMemo, BezDruckGLSMemo1, BezDruckGLSMemo2, BezDruckGLSMemo3, BezDruckGLSMemo4, BezDruckGLSMemo5, BezDruckGLSMemo6, BezDruckGLSMemo7, BezDruckGLSMemo8, BezDruckGLSMemo9, BezDruckGLSMemoA, BezDruckGSEPAMemo, BezDruckGSEPAMemo1, BezDruckGSEPAMemo2, BezDruckGSEPAMemo3, BezDruckGSEPAMemo4, BezDruckGSEPAMemo5, BezDruckGSEPAMemo6, BezDruckGSEPAMemo7, BezDruckGSEPAMemo8, BezDruckGSEPAMemo9, BezDruckGSEPAMemoA, BezDruckLSMemo, BezDruckLSMemo1, BezDruckLSMemo2, BezDruckLSMemo3, BezDruckLSMemo4, BezDruckLSMemo5, BezDruckLSMemo6, BezDruckLSMemo7, BezDruckLSMemo8, BezDruckLSMemo9, BezDruckLSMemoA, BezDruckSEPAMemo, BezDruckSEPAMemo1, BezDruckSEPAMemo2, BezDruckSEPAMemo3, BezDruckSEPAMemo4, BezDruckSEPAMemo5, BezDruckSEPAMemo6, BezDruckSEPAMemo7, BezDruckSEPAMemo8, BezDruckSEPAMemo9, BezDruckSEPAMemoA, NettoTage, Skonto, SkontoTage, Kunden, Lieferanten, AbbuchTage, AbbuchTageErst, AnlageUserID_, UserID_)
SELECT
  ZahlZiel = NewZahlZiel.TermNumber,
  ZahlZielBez = REPLACE(REPLACE(ZahlZiel.ZahlZielBez, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  ZahlZielBez1 = REPLACE(REPLACE(ZahlZiel.ZahlZielBez1, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  ZahlZielBez2 = REPLACE(REPLACE(ZahlZiel.ZahlZielBez2, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  ZahlZielBez3 = REPLACE(REPLACE(ZahlZiel.ZahlZielBez3, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  ZahlZielBez4 = REPLACE(REPLACE(ZahlZiel.ZahlZielBez4, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  ZahlZielBez5 = REPLACE(REPLACE(ZahlZiel.ZahlZielBez5, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  ZahlZielBez6 = REPLACE(REPLACE(ZahlZiel.ZahlZielBez6, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  ZahlZielBez7 = REPLACE(REPLACE(ZahlZiel.ZahlZielBez7, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  ZahlZielBez8 = REPLACE(REPLACE(ZahlZiel.ZahlZielBez8, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  ZahlZielBez9 = REPLACE(REPLACE(ZahlZiel.ZahlZielBez9, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  ZahlZielBezA = REPLACE(REPLACE(ZahlZiel.ZahlZielBezA, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckMemo = REPLACE(REPLACE(ZahlZiel.BezDruckMemo, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckMemo1 = REPLACE(REPLACE(ZahlZiel.BezDruckMemo1, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckMemo2 = REPLACE(REPLACE(ZahlZiel.BezDruckMemo2, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckMemo3 = REPLACE(REPLACE(ZahlZiel.BezDruckMemo3, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckMemo4 = REPLACE(REPLACE(ZahlZiel.BezDruckMemo4, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckMemo5 = REPLACE(REPLACE(ZahlZiel.BezDruckMemo5, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckMemo6 = REPLACE(REPLACE(ZahlZiel.BezDruckMemo6, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckMemo7 = REPLACE(REPLACE(ZahlZiel.BezDruckMemo7, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckMemo8 = REPLACE(REPLACE(ZahlZiel.BezDruckMemo8, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckMemo9 = REPLACE(REPLACE(ZahlZiel.BezDruckMemo9, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckMemoA = REPLACE(REPLACE(ZahlZiel.BezDruckMemoA, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckGMemo = REPLACE(REPLACE(ZahlZiel.BezDruckGMemo, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckGMemo1 = REPLACE(REPLACE(ZahlZiel.BezDruckGMemo1, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckGMemo2 = REPLACE(REPLACE(ZahlZiel.BezDruckGMemo2, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckGMemo3 = REPLACE(REPLACE(ZahlZiel.BezDruckGMemo3, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckGMemo4 = REPLACE(REPLACE(ZahlZiel.BezDruckGMemo4, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckGMemo5 = REPLACE(REPLACE(ZahlZiel.BezDruckGMemo5, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckGMemo6 = REPLACE(REPLACE(ZahlZiel.BezDruckGMemo6, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckGMemo7 = REPLACE(REPLACE(ZahlZiel.BezDruckGMemo7, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckGMemo8 = REPLACE(REPLACE(ZahlZiel.BezDruckGMemo8, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckGMemo9 = REPLACE(REPLACE(ZahlZiel.BezDruckGMemo9, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckGMemoA = REPLACE(REPLACE(ZahlZiel.BezDruckGMemoA, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckGLSMemo = REPLACE(REPLACE(ZahlZiel.BezDruckGLSMemo, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckGLSMemo1 = REPLACE(REPLACE(ZahlZiel.BezDruckGLSMemo1, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckGLSMemo2 = REPLACE(REPLACE(ZahlZiel.BezDruckGLSMemo2, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckGLSMemo3 = REPLACE(REPLACE(ZahlZiel.BezDruckGLSMemo3, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckGLSMemo4 = REPLACE(REPLACE(ZahlZiel.BezDruckGLSMemo4, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckGLSMemo5 = REPLACE(REPLACE(ZahlZiel.BezDruckGLSMemo5, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckGLSMemo6 = REPLACE(REPLACE(ZahlZiel.BezDruckGLSMemo6, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckGLSMemo7 = REPLACE(REPLACE(ZahlZiel.BezDruckGLSMemo7, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckGLSMemo8 = REPLACE(REPLACE(ZahlZiel.BezDruckGLSMemo8, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckGLSMemo9 = REPLACE(REPLACE(ZahlZiel.BezDruckGLSMemo9, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckGLSMemoA = REPLACE(REPLACE(ZahlZiel.BezDruckGLSMemoA, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckGSEPAMemo = REPLACE(REPLACE(ZahlZiel.BezDruckGSEPAMemo, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckGSEPAMemo1 = REPLACE(REPLACE(ZahlZiel.BezDruckGSEPAMemo1, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckGSEPAMemo2 = REPLACE(REPLACE(ZahlZiel.BezDruckGSEPAMemo2, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckGSEPAMemo3 = REPLACE(REPLACE(ZahlZiel.BezDruckGSEPAMemo3, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckGSEPAMemo4 = REPLACE(REPLACE(ZahlZiel.BezDruckGSEPAMemo4, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckGSEPAMemo5 = REPLACE(REPLACE(ZahlZiel.BezDruckGSEPAMemo5, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckGSEPAMemo6 = REPLACE(REPLACE(ZahlZiel.BezDruckGSEPAMemo6, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckGSEPAMemo7 = REPLACE(REPLACE(ZahlZiel.BezDruckGSEPAMemo7, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckGSEPAMemo8 = REPLACE(REPLACE(ZahlZiel.BezDruckGSEPAMemo8, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckGSEPAMemo9 = REPLACE(REPLACE(ZahlZiel.BezDruckGSEPAMemo9, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckGSEPAMemoA = REPLACE(REPLACE(ZahlZiel.BezDruckGSEPAMemoA, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckLSMemo = REPLACE(REPLACE(ZahlZiel.BezDruckLSMemo, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckLSMemo1 = REPLACE(REPLACE(ZahlZiel.BezDruckLSMemo1, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckLSMemo2 = REPLACE(REPLACE(ZahlZiel.BezDruckLSMemo2, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckLSMemo3 = REPLACE(REPLACE(ZahlZiel.BezDruckLSMemo3, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckLSMemo4 = REPLACE(REPLACE(ZahlZiel.BezDruckLSMemo4, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckLSMemo5 = REPLACE(REPLACE(ZahlZiel.BezDruckLSMemo5, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckLSMemo6 = REPLACE(REPLACE(ZahlZiel.BezDruckLSMemo6, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckLSMemo7 = REPLACE(REPLACE(ZahlZiel.BezDruckLSMemo7, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckLSMemo8 = REPLACE(REPLACE(ZahlZiel.BezDruckLSMemo8, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckLSMemo9 = REPLACE(REPLACE(ZahlZiel.BezDruckLSMemo9, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckLSMemoA = REPLACE(REPLACE(ZahlZiel.BezDruckLSMemoA, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckSEPAMemo = REPLACE(REPLACE(ZahlZiel.BezDruckSEPAMemo, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckSEPAMemo1 = REPLACE(REPLACE(ZahlZiel.BezDruckSEPAMemo1, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckSEPAMemo2 = REPLACE(REPLACE(ZahlZiel.BezDruckSEPAMemo2, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckSEPAMemo3 = REPLACE(REPLACE(ZahlZiel.BezDruckSEPAMemo3, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckSEPAMemo4 = REPLACE(REPLACE(ZahlZiel.BezDruckSEPAMemo4, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckSEPAMemo5 = REPLACE(REPLACE(ZahlZiel.BezDruckSEPAMemo5, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckSEPAMemo6 = REPLACE(REPLACE(ZahlZiel.BezDruckSEPAMemo6, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckSEPAMemo7 = REPLACE(REPLACE(ZahlZiel.BezDruckSEPAMemo7, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckSEPAMemo8 = REPLACE(REPLACE(ZahlZiel.BezDruckSEPAMemo8, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckSEPAMemo9 = REPLACE(REPLACE(ZahlZiel.BezDruckSEPAMemo9, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  BezDruckSEPAMemoA = REPLACE(REPLACE(ZahlZiel.BezDruckSEPAMemoA, N'15', FORMAT(NewZahlZiel.Discount, N'#.##')), N'25', CAST(NewZahlZiel.DaysToPay AS nvarchar)),
  NettoTage = NewZahlZiel.DaysToPay,
  Skonto = NewZahlZiel.Discount,
  SkontoTage = NewZahlZiel.DaysToPay,
  Kunden = ZahlZiel.Kunden,
  Lieferanten = ZahlZiel.Lieferanten,
  AbbuchTage = ZahlZiel.AbbuchTage,
  AbbuchTageErst = ZahlZiel.AbbuchTageErst,
  AnlageUserID_ = @userid,
  UserID_ = @userid
FROM ZahlZiel
CROSS JOIN @NewZahlZiel AS NewZahlZiel
WHERE ID = @sourceid;