ALTER INDEX [ContainID] ON [SCANS] REBUILD WITH (DATA_COMPRESSION = PAGE);
GO
ALTER INDEX [GrundID] ON [SCANS] REBUILD WITH (DATA_COMPRESSION = PAGE);
GO
ALTER INDEX [ArbPlatzID] ON [SCANS] REBUILD WITH (DATA_COMPRESSION = PAGE);
GO
ALTER INDEX [InvPoID] ON [SCANS] REBUILD WITH (DATA_COMPRESSION = PAGE);
GO
ALTER INDEX [TraegerID] ON [SCANS] REBUILD WITH (DATA_COMPRESSION = PAGE);
GO
ALTER INDEX [VsaID] ON [SCANS] REBUILD WITH (DATA_COMPRESSION = PAGE);
GO