USE master;
GO

ALTER DATABASE LaundryAutomation SET COMPATIBILITY_LEVEL = 150
ALTER DATABASE AdvanTexSyncLog SET COMPATIBILITY_LEVEL = 150
ALTER DATABASE AdvanTexSyncTestLog SET COMPATIBILITY_LEVEL = 150
ALTER DATABASE ArrivalLog SET COMPATIBILITY_LEVEL = 150
ALTER DATABASE ConsignmentLog SET COMPATIBILITY_LEVEL = 150
ALTER DATABASE EurosortLog SET COMPATIBILITY_LEVEL = 150
ALTER DATABASE FuturailLog SET COMPATIBILITY_LEVEL = 150
ALTER DATABASE GUILog SET COMPATIBILITY_LEVEL = 150
ALTER DATABASE HandLog SET COMPATIBILITY_LEVEL = 150
ALTER DATABASE IldefonsoLog SET COMPATIBILITY_LEVEL = 150
ALTER DATABASE JenrailLog SET COMPATIBILITY_LEVEL = 150
ALTER DATABASE ProductionLog_Budweis SET COMPATIBILITY_LEVEL = 150
ALTER DATABASE ProductionLog_Enns SET COMPATIBILITY_LEVEL = 150
ALTER DATABASE ProductionLog_Lenzing SET COMPATIBILITY_LEVEL = 150
ALTER DATABASE ProductionLog_Linz SET COMPATIBILITY_LEVEL = 150
ALTER DATABASE ProductionLog_Produktion_GP_Enns SET COMPATIBILITY_LEVEL = 150
ALTER DATABASE Productionlog_Rankweil SET COMPATIBILITY_LEVEL = 150
ALTER DATABASE ProductionLog_Test SET COMPATIBILITY_LEVEL = 150
ALTER DATABASE ProductionLog_Umlauft SET COMPATIBILITY_LEVEL = 150
ALTER DATABASE SushiTowerLog SET COMPATIBILITY_LEVEL = 150
ALTER DATABASE CustomerLog SET COMPATIBILITY_LEVEL = 150
ALTER DATABASE PerformanceVisualizationLog SET COMPATIBILITY_LEVEL = 150
ALTER DATABASE PositioningLog SET COMPATIBILITY_LEVEL = 150
ALTER DATABASE MoxaCoordinatorLog SET COMPATIBILITY_LEVEL = 150
ALTER DATABASE API_Log SET COMPATIBILITY_LEVEL = 150
ALTER DATABASE ArrivalLog_StPoelten SET COMPATIBILITY_LEVEL = 150
ALTER DATABASE ProductionLog_Brasov SET COMPATIBILITY_LEVEL = 150
ALTER DATABASE ProductionLog_SCHI SET COMPATIBILITY_LEVEL = 150
ALTER DATABASE ProductionLog_SMZL SET COMPATIBILITY_LEVEL = 150
ALTER DATABASE IldefonsoLog2 SET COMPATIBILITY_LEVEL = 150
ALTER DATABASE Reporting SET COMPATIBILITY_LEVEL = 150
ALTER DATABASE EuroSortOptimierung SET COMPATIBILITY_LEVEL = 150
ALTER DATABASE PerformanceVisualization SET COMPATIBILITY_LEVEL = 150
ALTER DATABASE AdvantexSync_Log_Temp SET COMPATIBILITY_LEVEL = 150
ALTER DATABASE CustomerSystem SET COMPATIBILITY_LEVEL = 150
ALTER DATABASE AdvanTexSync SET COMPATIBILITY_LEVEL = 150
ALTER DATABASE CustomerSystemTest SET COMPATIBILITY_LEVEL = 150
ALTER DATABASE PerformanceVisualizationTest SET COMPATIBILITY_LEVEL = 150
ALTER DATABASE LaundryAutomationTest SET COMPATIBILITY_LEVEL = 150
ALTER DATABASE AdvanTexSyncTest SET COMPATIBILITY_LEVEL = 150

GO